name: Java CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Execute Tests
        run: mvn test

  mutation-testing:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master' || github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'master' # Use 'master' branch for mutation testing

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Install Mutation Testing Tool (e.g., PITest)
        run: mvn test-compile org.pitest:pitest-maven:mutationCoverage
          
          

      - name: Save Mutation Testing Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: mutation-report
          path: target/pit-reports