name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
    Build-Java-Project:
        runs-on: ubuntu-latest
        steps:
          - name: Set up JDK
            uses: actions/setup-java@v2
            with:
              java-version: '20' # You can change this to the Java version you need
          - name: Build with Maven
            run: |
              cd /java 
              mvn clean install  

